config/routes.rb
Passty::Application.routes.draw do
  resources :applications do
    resources :passwords
  end

  resource :migrate

  devise_for :users

  root 'applications#index'
end

app/models/application.rb
# == Schema Information
#
# Table name: applications
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  url         :string(255)
#  description :text
#  user_id     :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class Application < ActiveRecord::Base
  belongs_to :user

  has_many :passwords, dependent: :destroy

  validates :title, presence: true

  def self.search(query)
    where("lower(applications.title) LIKE :query OR applications.url LIKE :query OR lower(applications.description) LIKE :query", query: "%#{query.downcase}%")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authenticate_user!
  before_filter :default_headers

  def default_headers
    headers['X-Frame-Options'] = 'DENY'
    headers['X-XSS-Protection'] = '1; mode=block'
  end

  def migrate_old_passwords
    if current_user.passwords.old.any?
      redirect_to migrate_path
    end
  end
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  before_filter :migrate_old_passwords
  before_action :set_application, only: [:show, :edit, :update, :destroy]

  # GET /applications
  # GET /applications.json
  def index
    @applications = current_user.applications
    @applications = @applications.search(params[:search]) if params[:search].present?

    @sort = params[:sort]

    @applications = case @sort
                    when 'newest'
                      @applications.reorder('applications.created_at DESC')
                    when 'oldest'
                      @applications.reorder('applications.created_at ASC')
                    else
                      @applications.reorder('applications.title ASC')
                    end

    @applications = @applications.page(params[:page] || 0).per(40)
  end

  # GET /applications/1
  # GET /applications/1.json
  def show
    @passwords = @application.passwords
  end

  # GET /applications/new
  def new
    @application = current_user.applications.new
  end

  # GET /applications/1/edit
  def edit
  end

  # POST /applications
  # POST /applications.json
  def create
    @application = current_user.applications.new(application_params)

    respond_to do |format|
      if @application.save
        format.html { redirect_to @application, notice: 'Application was successfully created.' }
        format.json { render action: 'show', status: :created, location: @application }
      else
        format.html { render action: 'new' }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applications/1
  # PATCH/PUT /applications/1.json
  def update
    respond_to do |format|
      if @application.update(application_params)
        format.html { redirect_to @application, notice: 'Application was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applications/1
  # DELETE /applications/1.json
  def destroy
    @application.destroy
    respond_to do |format|
      format.html { redirect_to applications_url }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_application
    @application = current_user.applications.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def application_params
    params.require(:application).permit(:title, :url, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user_gravatar(size = 24)
    gravatar_path(current_user.email, size)
  end

  def gravatar_path(user_email, size = 24)
    gravatar_prefix = request.ssl? ? "https://secure" : "http://www"
    user_email.strip!
    "#{gravatar_prefix}.gravatar.com/avatar/#{Digest::MD5.hexdigest(user_email.downcase)}?s=#{size}&d=mm"
  end
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/views/applications/_form.html.haml
= form_for @application do |f|
  - if @application.errors.any?
    #error_explanation
      %h2= "#{pluralize(@application.errors.count, "error")} prohibited this application from being saved:"
      %ul
        - @application.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control', placeholder: 'GMail'
  .form-group
    = f.label :url
    = f.text_field :url, class: 'form-control', placeholder: 'http://mail.google.com'
  .form-group
    = f.label :description
    = f.text_area :description, class: 'form-control', placeholder: 'email application'
  .form-actions
    - if @application.new_record?
      = f.submit 'Create', class: 'btn btn-primary btn-success'
    - else
      = f.submit 'Save', class: 'btn btn-primary'

app/views/applications/edit.html.haml
= content_for :title do
  %h2 Editing application

= render 'form'

app/views/applications/index.html.haml
= content_for :title do
  %h2
    Listing applications
    .pull-right
      = link_to 'New Application', new_application_path, class: 'btn btn-success'

.clearfix
  = form_tag applications_path, class: 'form-inline search-form', method: :get do
    = search_field_tag :search, params[:search], class: 'form-control input-sm'
    = submit_tag 'Search', class: 'btn btn-default btn-sm'
    .pull-right
      .dropdown.inline
        %a.dropdown-toggle{href: '#', "data-toggle" => "dropdown"}
          %span.light sort:
          - if @sort.present?
            = @sort.humanize
          - else
            Name
          %b.caret
        %ul.dropdown-menu
          %li
            = link_to applications_path(sort: nil) do
              Name
            = link_to applications_path(sort: 'newest') do
              Newest
            = link_to applications_path(sort: 'oldest') do
              Oldest

%table.table
  %tr
    %th Title
    %th Passwords
    %th Url
    %th Description
    %th

  - @applications.each do |application|
    %tr
      %td
        %i.icon-star-empty.cgray
        = link_to application_path(application) do
          %strong= application.title
      %td.light
        %strong= application.passwords.count
      %td
        %small
          = link_to application.url, application.url, target: '_blank'
      %td
        %small.cgray
          = application.description
      %td
        .pull-right
          = link_to 'Edit', edit_application_path(application)
          &nbsp;
          = link_to 'Destroy', application, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br
= paginate @applications

app/views/applications/new.html.haml
= content_for :title do
  %h2 New application

= render 'form'

app/views/applications/show.html.haml
= content_for :title do
  %h2
    = link_to 'Apps', applications_path
    %i.icon-angle-right.cgray
    = @application.title
    .pull-right
      = link_to 'Edit', edit_application_path(@application), class: 'btn btn-default'


- if @application.url.present?
  %p
    %b Url:
    = link_to @application.url, @application.url

- if @application.description.present?
  %p
    %b Description:
    = @application.description


%h3
  Passwords:
  = link_to 'New Password', new_application_password_path(@application), class: 'btn btn-success pull-right btn-sm'

= render 'passwords/list'